import { ChevronLeft, ChevronRight, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Category, ExecutionSettings, StudyInterval, StudySession, Task, WorkloadTarget } from "../domain/models";
import { analysisRange, buildCategoryWorkload, type AnalysisPeriod } from "../domain/workloadAnalysis";
import { executionAdapter, formatDuration } from "../features/executionAdapter";

const todayKey = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const percent = (value: number | null) => value === null ? "—" : `${Math.round(value * 100)}%`;
const shift = (anchor: string, period: AnalysisPeriod, by: -1 | 1) => { const date = new Date(`${anchor}T12:00:00`); date.setDate(date.getDate() + by * (period === "week" ? 7 : 31)); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };

export function AnalysisPage({ categories, tasks, sessions, settings, onSaveTargets }: { categories: Category[]; tasks: Task[]; sessions: StudySession[]; settings: ExecutionSettings | null; onSaveTargets: (targets: WorkloadTarget[]) => Promise<void> }) {
  const [period, setPeriod] = useState<AnalysisPeriod>("week"), [anchor, setAnchor] = useState(todayKey), [targets, setTargets] = useState<WorkloadTarget[]>(settings?.workloadTargets ?? []), [intervals, setIntervals] = useState<Record<string, StudyInterval[]>>({}), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false);
  useEffect(() => setTargets(settings?.workloadTargets ?? []), [settings?.workloadTargets]);
  useEffect(() => { let cancelled = false; setLoading(true); void Promise.all(sessions.map(async session => [session.id, await executionAdapter.listIntervals(session.id)] as const)).then(entries => { if (!cancelled) { setIntervals(Object.fromEntries(entries)); setLoading(false); } }); return () => { cancelled = true; }; }, [sessions]);
  const range = useMemo(() => analysisRange(period, anchor), [period, anchor]);
  const rows = useMemo(() => buildCategoryWorkload({ categories, tasks, sessions, intervalsBySession: intervals, targets, range }), [categories, tasks, sessions, intervals, targets, range]);
  const target = (id: string) => targets.find(item => item.categoryId === id)?.plannedActions ?? 0;
  const update = (categoryId: string, plannedActions: number) => setTargets(current => [...current.filter(item => item.categoryId !== categoryId), { categoryId, plannedActions: Math.max(0, Math.min(99, plannedActions || 0)) }]);
  const save = async () => { setSaving(true); try { await onSaveTargets(targets.filter(item => item.plannedActions > 0)); } finally { setSaving(false); } };
  const hasPlan = targets.some(item => item.plannedActions > 0);
  return <><header className="page-header"><div><p className="eyebrow">历史分析</p><h1>让实际投入回到你的计划里</h1><p>用可完成的行动量设定方向，再用每周或每月的真实记录检查偏差。</p></div></header><section className="analysis-intro"><strong>计划行动量不是预计分钟数。</strong><span>把“完成线性代数练习 1”这类可独立完成的事项算作 1；任务太大时，先拆成几步再填写。</span></section><section className="analysis-controls"><div className="segmented"><button className={period === "week" ? "active" : ""} onClick={() => setPeriod("week")}>按周</button><button className={period === "month" ? "active" : ""} onClick={() => setPeriod("month")}>按月</button></div><div className="analysis-range"><button aria-label="上一周期" onClick={() => setAnchor(shift(anchor, period, -1))}><ChevronLeft /></button><strong>{range.label}</strong><button aria-label="下一周期" onClick={() => setAnchor(shift(anchor, period, 1))}><ChevronRight /></button></div></section><section className="analysis-targets"><header><div><h2>本周计划行动量</h2><p>它定义各科目的理想比例；按月查看时，仍用同一比例作为对照。</p></div><button className="button primary" disabled={saving} onClick={() => void save()}><Save />{saving ? "保存中…" : "保存计划行动量"}</button></header><div className="analysis-target-grid">{categories.filter(category => !category.archivedAt).map(category => <label key={category.id}><span>{category.name}</span><input aria-label={`${category.name} 计划行动量`} type="number" min="0" max="99" value={target(category.id)} onChange={event => update(category.id, Number(event.target.value))}/><small>个可完成行动</small></label>)}</div></section><section className="analysis-results"><header><div><h2>{range.label}的计划与实际</h2><p>完成行动比例决定是否偏离；专注时长只帮助理解投入去了哪里。</p></div></header>{loading ? <div className="empty-state"><h3>正在汇总历史专注记录…</h3></div> : !hasPlan ? <div className="empty-state"><h3>先为每个科目填写本周计划行动量</h3><p>保存后，StudyFlow 才能判断实际完成分布是否偏离你的计划。</p></div> : <div className="analysis-table"><div className="analysis-table-head"><span>科目</span><span>计划比例</span><span>完成行动</span><span>实际比例</span><span>偏差</span><span>专注时长</span></div>{rows.filter(row => row.plannedActions > 0 || row.completedActions > 0 || row.focusSeconds > 0).map(row => <article key={row.categoryId}><strong>{row.categoryName}</strong><span>{percent(row.plannedShare)}</span><span>{row.completedActions} 个</span><span>{percent(row.completedShare)}</span><span className={row.deviationPoints === null ? "" : row.deviationPoints < -15 ? "analysis-low" : row.deviationPoints > 15 ? "analysis-high" : "analysis-balanced"}>{row.deviationPoints === null ? "记录不足" : `${row.deviationPoints > 0 ? "+" : ""}${row.deviationPoints} 个百分点`}</span><span>{formatDuration(row.focusSeconds)}</span><p>{row.deviationPoints === null ? "本周期还没有足够的完成记录。" : row.deviationPoints < -15 ? "投入偏少：下周期增加这个科目的可完成行动。" : row.deviationPoints > 15 ? "投入偏多：检查是否挤占了其他科目的计划。" : "与计划接近。"}</p></article>)}</div>}</section></>;
}
