import { ChevronLeft, ChevronRight, Save } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { Category, StudyInterval, StudySession, Task, WeeklyWorkloadPlan } from "../domain/models";
import { analysisRange, buildCategoryWorkload, buildDailyWorkload, buildWeeklySummaries, nextWeekAdvice, type AnalysisPeriod } from "../domain/workloadAnalysis";
import { executionAdapter, formatDuration } from "../features/executionAdapter";
import { studyFlowApi } from "../features/api";

const todayKey = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
const shift = (anchor: string, period: AnalysisPeriod, by: -1 | 1) => { const date = new Date(`${anchor}T12:00:00`); date.setDate(date.getDate() + by * (period === "week" ? 7 : 31)); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; };
const weekStart = (date: string) => analysisRange("week", date).from;

function Ring({ title, values }: { title: string; values: Array<{ label: string; value: number }> }) {
  const total = values.reduce((sum, item) => sum + item.value, 0); let cursor = 0;
  const stops = total ? values.filter((item) => item.value > 0).map((item, index) => { const start = cursor / total * 100; cursor += item.value; return `var(--chart-${index % 5}) ${start}% ${cursor / total * 100}%`; }).join(", ") : "#e6ece7 0 100%";
  return <section className="analysis-ring"><h3>{title}</h3><div className="ring" style={{ background: `conic-gradient(${stops})` }}><strong>{total}</strong><small>行动</small></div><ul>{values.filter((item) => item.value > 0).map((item, index) => <li key={item.label}><i style={{ background: `var(--chart-${index % 5})` }}/>{item.label}<span>{item.value}</span></li>)}</ul></section>;
}

export function AnalysisPage({ categories, tasks, sessions }: { categories: Category[]; tasks: Task[]; sessions: StudySession[] }) {
  const [period, setPeriod] = useState<AnalysisPeriod>("week"), [anchor, setAnchor] = useState(todayKey), [plans, setPlans] = useState<WeeklyWorkloadPlan[]>([]), [intervals, setIntervals] = useState<Record<string, StudyInterval[]>>({}), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [total, setTotal] = useState(0), [allocations, setAllocations] = useState<Record<string, number>>({}), [message, setMessage] = useState("");
  const range = useMemo(() => analysisRange(period, anchor), [period, anchor]);
  const selectedWeekStart = weekStart(anchor);
  const currentPlan = plans.find((plan) => plan.weekStart === selectedWeekStart);
  useEffect(() => { let cancelled = false; void Promise.all([studyFlowApi.weeklyWorkloadPlans.list(), Promise.all(sessions.map(async session => [session.id, await executionAdapter.listIntervals(session.id)] as const))]).then(([nextPlans, entries]) => { if (!cancelled) { setPlans(nextPlans); setIntervals(Object.fromEntries(entries)); setLoading(false); } }); return () => { cancelled = true; }; }, [sessions]);
  useEffect(() => { if (period === "week") { const plan = plans.find((item) => item.weekStart === selectedWeekStart); if (plan) { setTotal(plan.totalPlannedActions); setAllocations(Object.fromEntries(plan.allocations.map((item) => [item.categoryId, item.plannedActions]))); } else { setTotal(0); setAllocations({}); } setMessage(""); } }, [period, plans, selectedWeekStart]);
  const rows = useMemo(() => buildCategoryWorkload({ categories, tasks, sessions, intervalsBySession: intervals, plan: period === "week" ? currentPlan : undefined, range }), [categories, tasks, sessions, intervals, currentPlan, period, range]);
  const daily = useMemo(() => period === "week" ? buildDailyWorkload(tasks, sessions, intervals, range) : [], [tasks, sessions, intervals, period, range]);
  const summaries = useMemo(() => buildWeeklySummaries(plans, tasks, sessions, intervals, range), [plans, tasks, sessions, intervals, range]);
  const completed = rows.reduce((sum, row) => sum + row.completedActions, 0), focused = rows.reduce((sum, row) => sum + row.focusSeconds, 0), allocated = Object.values(allocations).reduce((sum, value) => sum + value, 0);
  const advice = useMemo(() => nextWeekAdvice(rows, currentPlan, buildWeeklySummaries(plans, tasks, sessions, intervals, { from: "1900-01-01", to: "2999-12-31", label: "全部" })), [rows, currentPlan, plans, tasks, sessions, intervals]);
  const savePlan = async () => { if (total < 1 || allocated !== total) { setMessage(`请让各科目分配之和等于总量（当前 ${allocated}/${total || 0}）。`); return; } setSaving(true); try { const plan = await studyFlowApi.weeklyWorkloadPlans.save({ weekStart: selectedWeekStart, totalPlannedActions: total, allocations: categories.filter((category) => (allocations[category.id] ?? 0) > 0).map((category) => ({ categoryId: category.id, categoryNameSnapshot: category.name, plannedActions: allocations[category.id] })) }); setPlans((current) => [...current.filter((item) => item.weekStart !== plan.weekStart), plan].sort((a, b) => a.weekStart.localeCompare(b.weekStart))); setMessage("本周最低行动计划已保存。"); } finally { setSaving(false); } };
  const maxDaily = Math.max(1, ...daily.map((item) => item.completedActions));
  return <><header className="page-header"><div><p className="eyebrow">学习计划教练</p><h1>让实际投入回到你的计划里</h1><p>先设定可完成的最低行动量，再用真实记录调整下一周。</p></div></header><section className="analysis-controls"><div className="segmented"><button className={period === "week" ? "active" : ""} onClick={() => setPeriod("week")}>按周</button><button className={period === "month" ? "active" : ""} onClick={() => setPeriod("month")}>按月</button></div><div className="analysis-range"><button aria-label="上一周期" onClick={() => setAnchor(shift(anchor, period, -1))}><ChevronLeft /></button><strong>{range.label}</strong><button aria-label="下一周期" onClick={() => setAnchor(shift(anchor, period, 1))}><ChevronRight /></button></div></section>
  {period === "week" && <section className="analysis-targets"><header><div><h2>本周最低行动计划</h2><p>完成一个有明确结束条件的日行动，计为 1 个行动；不使用预计时长作为计划单位。</p></div><button className="button primary" disabled={saving} onClick={() => void savePlan()}><Save />{saving ? "保存中…" : "保存本周计划"}</button></header><label className="analysis-total"><span>本周最低总量</span><input aria-label="本周最低行动总量" type="number" min="1" max="200" value={total || ""} onChange={(event) => setTotal(Number(event.target.value))}/><small>个行动</small><strong>已分配 {allocated}/{total || 0}</strong></label><div className="analysis-target-grid">{categories.filter((category) => !category.archivedAt).map((category) => <label key={category.id}><span>{category.name}</span><input aria-label={`${category.name} 本周行动量`} type="number" min="0" max="200" value={allocations[category.id] ?? 0} onChange={(event) => setAllocations((current) => ({ ...current, [category.id]: Number(event.target.value) }))}/><small>个行动</small></label>)}</div>{message && <p role="status" className="analysis-message">{message}</p>}</section>}
  {loading ? <div className="empty-state"><h3>正在汇总历史专注记录…</h3></div> : <><section className="analysis-overview"><article><small>{period === "week" ? "最低计划" : "实际完成"}</small><strong>{period === "week" && currentPlan ? `${completed} / ${currentPlan.totalPlannedActions}` : `${completed}`}</strong><span>个行动</span></article><article><small>总专注时长</small><strong>{formatDuration(focused)}</strong><span>按实际时间区间统计</span></article><article><small>{period === "week" && currentPlan ? "剩余最低行动" : "参与科目"}</small><strong>{period === "week" && currentPlan ? Math.max(0, currentPlan.totalPlannedActions - completed) : rows.length}</strong><span>{period === "week" && currentPlan ? "个行动" : "个分类"}</span></article></section>
  {period === "week" && !currentPlan ? <div className="empty-state"><h3>先设定本周最低行动计划</h3><p>总量与科目分配会成为本周分析和下周建议的基准。</p></div> : <><section className="analysis-visuals"><Ring title="计划行动分配" values={rows.map((row) => ({ label: row.categoryName, value: row.plannedActions }))}/><Ring title="实际完成分配" values={rows.map((row) => ({ label: row.categoryName, value: row.completedActions }))}/>{period === "week" && <section className="analysis-rhythm"><h3>一周完成节奏</h3><div>{daily.map((item) => <span key={item.date} title={`${item.label}：${item.completedActions} 个行动，${formatDuration(item.focusSeconds)}`}><i style={{ height: `${Math.max(4, item.completedActions / maxDaily * 100)}%` }}/><small>{item.label}</small><b>{item.completedActions}</b></span>)}</div></section>}</section><section className="analysis-results"><header><div><h2>{period === "week" ? "各科目兑现情况" : "当月实际投入"}</h2><p>专注时长帮助理解投入去了哪里；完成行动才是计划兑现的依据。</p></div></header><div className="analysis-table"><div className="analysis-table-head"><span>科目</span><span>计划</span><span>完成</span><span>差额</span><span>专注时长</span><span>每行动时长</span></div>{rows.map((row) => <article key={row.categoryId}><strong>{row.categoryName}</strong><span>{row.plannedActions || "—"}</span><span>{row.completedActions}</span><span>{row.plannedActions ? `${row.remainingActions ? `还差 ${row.remainingActions}` : "已达成"}` : "计划外"}</span><span>{formatDuration(row.focusSeconds)}</span><span>{row.averageFocusSeconds === null ? "—" : formatDuration(row.averageFocusSeconds)}</span></article>)}</div></section>{period === "month" && <section className="analysis-results"><header><div><h2>本月开始的周计划</h2><p>月度不额外设目标；这里汇总每周最低计划及兑现结果。</p></div></header><div className="weekly-summary">{summaries.length ? summaries.map((item) => <article key={item.weekStart}><strong>{item.label}</strong><span>{item.completedActions} / {item.plannedActions} 个行动</span><small>{formatDuration(item.focusSeconds)}</small></article>) : <p>本月尚未建立周计划。</p>}</div></section>}{period === "week" && <section className="analysis-coach"><h2>下周建议</h2>{advice.map((item) => <p key={item}>• {item}</p>)}</section>}</>}</>}</>;
}
