import { useEffect, useState, type FormEvent } from "react";
import type { ExecutionSettings } from "../features/executionTypes";

export function ExecutionSettingsPage({ settings, onSave }: { settings: ExecutionSettings | null; onSave: (value: Partial<ExecutionSettings>) => Promise<void> }) {
 const [draft,setDraft]=useState(settings);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);
 useEffect(()=>setDraft(settings),[settings]); if(!draft)return <p>正在读取设置…</p>;
 async function submit(e:FormEvent){e.preventDefault();const value=draft;if(!value)return;setSaving(true);setSaved(false);try{await onSave(value);setSaved(true)}finally{setSaving(false)}}
 return <><header className="page-header"><div><p className="eyebrow">Execution</p><h1>专注设置</h1><p>调整番茄节奏与计时提醒。更改只影响之后开始的会话。</p></div></header><form className="settings-panel" onSubmit={e=>void submit(e)}><section><div><h2>番茄钟</h2><p>设置一组专注与休息的节奏。</p></div><div className="settings-grid"><NumberField label="专注时长" value={draft.focusMinutes} min={1} max={180} onChange={focusMinutes=>setDraft({...draft,focusMinutes})}/><NumberField label="短休息" value={draft.shortBreakMinutes} min={1} max={60} onChange={shortBreakMinutes=>setDraft({...draft,shortBreakMinutes})}/><NumberField label="长休息" value={draft.longBreakMinutes} min={1} max={120} onChange={longBreakMinutes=>setDraft({...draft,longBreakMinutes})}/><NumberField label="每组轮数" unit="轮" value={draft.roundsPerSet} min={1} max={12} onChange={roundsPerSet=>setDraft({...draft,roundsPerSet})}/></div></section><section><div><h2>安全与提醒</h2><p>避免忘记停止计时，并选择阶段完成时的提醒方式。</p></div><div className="settings-grid"><NumberField label="正计时自动暂停" value={draft.stopwatchAutoPauseMinutes} min={60} max={1440} onChange={stopwatchAutoPauseMinutes=>setDraft({...draft,stopwatchAutoPauseMinutes})}/><label className="setting-switch"><span><strong>提示音</strong><small>阶段结束时播放短提示音</small></span><input type="checkbox" checked={draft.soundEnabled} onChange={e=>setDraft({...draft,soundEnabled:e.target.checked})}/></label><label className="setting-switch"><span><strong>浏览器通知</strong><small>需要浏览器授予通知权限</small></span><input type="checkbox" checked={draft.notificationsEnabled} onChange={e=>setDraft({...draft,notificationsEnabled:e.target.checked})}/></label></div></section><footer><span>{saved?"设置已保存":"所有设置仅保存在当前浏览器"}</span><button className="button primary" disabled={saving}>{saving?"正在保存…":"保存设置"}</button></footer></form></>;
}
function NumberField({label,value,min,max,unit="分钟",onChange}:{label:string;value:number;min:number;max:number;unit?:string;onChange:(n:number)=>void}){return <label className="field"><span>{label}</span><div className="number-input"><input type="number" value={value} min={min} max={max} onChange={e=>onChange(Number(e.target.value))}/><small>{unit}</small></div></label>}
