import { useCallback, useEffect, useState, type FormEvent } from "react";
import { AMBIENT_SOUNDS, COMPLETION_SOUNDS, type AmbientSound } from "../features/focusAudio";
import type { ExecutionSettings } from "../features/executionTypes";
import { authAdapter, type AuthUser } from "../features/authAdapter";
import { confirmFirstMerge, createLocalBackup, initializeCloudSync, syncNow, type MergeSummary, type SyncStatus } from "../features/syncService";

type Props = { settings: ExecutionSettings | null; onSave: (value: Partial<ExecutionSettings>) => Promise<void>; onPreviewCompletionSound: (value: Pick<ExecutionSettings, "completionSound" | "ambientSound" | "soundVolume">) => void; onPreviewAmbientSound: (sound: AmbientSound, volume: number) => void };

export function ExecutionSettingsPage({ settings, onSave, onPreviewCompletionSound, onPreviewAmbientSound }: Props) {
  const [draft, setDraft] = useState(settings); const [saving, setSaving] = useState(false); const [saved, setSaved] = useState(false);
  useEffect(() => setDraft(settings), [settings]);
  if (!draft) return <p>正在读取设置…</p>;
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setSaved(false); try { await onSave(draft as Partial<ExecutionSettings>); setSaved(true); } finally { setSaving(false); } }
  return <><header className="page-header"><div><p className="eyebrow">Execution</p><h1>专注设置</h1><p>调整番茄节奏、自然环境声与阶段结束提醒。</p></div></header><form className="settings-panel" onSubmit={(event) => void submit(event)}>
    <section><div><h2>番茄钟</h2><p>设置一组专注与休息的节奏。</p></div><div className="settings-grid"><NumberField label="专注时长" value={draft.focusMinutes} min={1} max={180} onChange={(focusMinutes) => setDraft({ ...draft, focusMinutes })} /><NumberField label="短休息" value={draft.shortBreakMinutes} min={1} max={60} onChange={(shortBreakMinutes) => setDraft({ ...draft, shortBreakMinutes })} /><NumberField label="长休息" value={draft.longBreakMinutes} min={1} max={120} onChange={(longBreakMinutes) => setDraft({ ...draft, longBreakMinutes })} /><NumberField label="每组轮数" unit="轮" value={draft.roundsPerSet} min={1} max={12} onChange={(roundsPerSet) => setDraft({ ...draft, roundsPerSet })} /></div></section>
    <section><div><h2>专注声音</h2><p>环境声只在正在专注时播放。</p></div><div className="settings-grid"><label className="field"><span>环境声</span><select value={draft.ambientSound} onChange={(event) => setDraft({ ...draft, ambientSound: event.target.value as AmbientSound })}>{Object.entries(AMBIENT_SOUNDS).map(([value, option]) => <option key={value} value={value}>{option.label}</option>)}</select></label><div className={`volume-setting${draft.ambientSound === "off" ? " disabled" : ""}`}><label htmlFor="ambient-volume"><span><strong>环境音音量</strong></span><output>{draft.ambientVolume}%</output></label><input id="ambient-volume" aria-label="环境音音量" type="range" min="10" max="100" step="5" disabled={draft.ambientSound === "off"} value={draft.ambientVolume} onChange={(event) => setDraft({ ...draft, ambientVolume: Number(event.target.value) })} /><button className="button secondary" type="button" disabled={draft.ambientSound === "off"} onClick={() => onPreviewAmbientSound(draft.ambientSound, draft.ambientVolume)}>试听环境声</button></div></div></section>
    <section><div><h2>安全与提醒</h2><p>避免忘记停止计时，并选择阶段结束时的提醒方式。</p></div><div className="settings-grid"><NumberField label="正计时自动暂停" value={draft.stopwatchAutoPauseMinutes} min={60} max={1440} onChange={(stopwatchAutoPauseMinutes) => setDraft({ ...draft, stopwatchAutoPauseMinutes })} /><label className="setting-switch"><span><strong>提示音</strong><small>阶段结束时播放提示音</small></span><input type="checkbox" checked={draft.soundEnabled} onChange={(event) => setDraft({ ...draft, soundEnabled: event.target.checked })} /></label><label className="field"><span>结束提示音</span><select disabled={!draft.soundEnabled} value={draft.completionSound} onChange={(event) => setDraft({ ...draft, completionSound: event.target.value as ExecutionSettings["completionSound"] })}>{Object.entries(COMPLETION_SOUNDS).map(([value, option]) => <option key={value} value={value}>{option.label}</option>)}<option value="follow-ambience">跟随环境声</option></select></label><div className={`volume-setting${draft.soundEnabled ? "" : " disabled"}`}><label htmlFor="sound-volume"><span><strong>提示音音量</strong></span><output>{draft.soundVolume}%</output></label><input id="sound-volume" aria-label="提示音音量" type="range" min="10" max="100" step="5" disabled={!draft.soundEnabled} value={draft.soundVolume} onChange={(event) => setDraft({ ...draft, soundVolume: Number(event.target.value) })} /><button className="button secondary" type="button" disabled={!draft.soundEnabled} onClick={() => onPreviewCompletionSound(draft)}>试听提示音</button></div><label className="setting-switch"><span><strong>浏览器通知</strong><small>需要浏览器授权通知权限</small></span><input type="checkbox" checked={draft.notificationsEnabled} onChange={(event) => setDraft({ ...draft, notificationsEnabled: event.target.checked })} /></label></div></section>
    <footer><span>{saved ? "设置已保存" : "声音设置只影响之后开始的会话"}</span><button className="button primary" disabled={saving}>{saving ? "正在保存…" : "保存设置"}</button></footer>
  </form><SyncSettings /></>;
}

function NumberField({ label, value, min, max, unit = "分钟", onChange }: { label: string; value: number; min: number; max: number; unit?: string; onChange: (value: number) => void }) { return <label className="field"><span>{label}</span><div className="number-input"><input type="number" value={value} min={min} max={max} onChange={(event) => onChange(Number(event.target.value))} /><small>{unit}</small></div></label>; }

function SyncSettings() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [mode, setMode] = useState<"login" | "signup">("login"); const [user, setUser] = useState<AuthUser | null>(null); const [status, setStatus] = useState<SyncStatus>(authAdapter.isConfigured() ? "signed-out" : "not-configured"); const [message, setMessage] = useState(""); const [mergeSummary, setMergeSummary] = useState<MergeSummary | null>(null); const [loading, setLoading] = useState(false);
  const initialize = useCallback(async () => { const state = await initializeCloudSync(); setStatus(state.result.status); setMergeSummary(state.mergeSummary); setMessage(state.result.error ?? (state.result.uploaded > 0 || state.result.downloaded > 0 ? `自动同步完成：上传 ${state.result.uploaded} 条，下载 ${state.result.downloaded} 条` : "云端数据已是最新状态")); }, []);
  const loadUser = useCallback(async () => { const next = await authAdapter.getUser(); setUser(next); setStatus(next ? "synced" : "signed-out"); if (next) await initialize(); }, [initialize]);
  useEffect(() => { let mounted = true; void authAdapter.handleCallback().then(() => { if (mounted) void loadUser(); }).catch((error) => mounted && setMessage(error instanceof Error ? error.message : "登录失败")); const unsubscribe = authAdapter.onAuthStateChange((next) => { if (!mounted) return; setUser(next); setStatus(next ? "synced" : "signed-out"); if (next) void initialize(); }); return () => { mounted = false; unsubscribe(); }; }, [initialize, loadUser]);
  const submitAuth = useCallback(async () => { setLoading(true); setMessage(""); try { const result = mode === "signup" ? await authAdapter.signUp(email, password) : await authAdapter.signIn(email, password); setUser(result.user); if (result.needsEmailConfirmation) setMessage("注册成功，请先到邮箱完成确认，再登录"); else await initialize(); } catch (error) { setMessage(error instanceof Error ? error.message : "认证失败"); } finally { setLoading(false); } }, [email, initialize, mode, password]);
  const sync = useCallback(async () => { setLoading(true); setMessage("正在同步…"); try { const result = await syncNow(); setStatus(result.status); setMessage(result.error ?? `已上传 ${result.uploaded} 条，下载 ${result.downloaded} 条`); } finally { setLoading(false); } }, []);
  const merge = useCallback(async (strategy: "keep-local" | "merge") => { setLoading(true); setMessage("正在合并本地与云端数据…"); try { const result = await confirmFirstMerge(strategy); setStatus(result.status); if (result.status === "synced") setMergeSummary(null); setMessage(result.error ?? `合并完成：上传 ${result.uploaded} 条，下载 ${result.downloaded} 条`); } finally { setLoading(false); } }, []);
  const backup = useCallback(async () => { const blob = await createLocalBackup(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `studyflow-backup-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); }, []);
  const statusLabel: Record<SyncStatus, string> = { "not-configured": "未配置", "signed-out": "未登录", synced: "已同步", offline: "设备确实处于离线状态", error: "同步出错" };
  if (!authAdapter.isConfigured()) return <section className="settings-panel sync-settings"><h2>跨设备同步</h2><p className="inline-warning">尚未配置云同步服务，当前继续使用本地模式。</p></section>;
  return <section className="settings-panel sync-settings"><header><div><p className="eyebrow">Cloud Sync</p><h2>跨设备同步</h2><p>同一账号登录后自动同步；“立即同步”只用于手动重试。</p></div></header>{user ? <div className="sync-actions"><p>已登录：{user.email ?? "账号用户"}</p>{mergeSummary && <div className="sync-merge"><strong>两边都有独立数据，请确认一次</strong><span>本地 {mergeSummary.localCount} 条，云端 {mergeSummary.remoteCount} 条</span><button className="button primary" type="button" disabled={loading} onClick={() => void merge("merge")}>{loading ? "正在合并…" : "安全合并本地与云端"}</button></div>}<button className="button secondary" type="button" disabled={loading || Boolean(mergeSummary)} onClick={() => void sync()}>{loading ? "同步中…" : "立即同步"}</button><button className="button secondary" type="button" onClick={() => void backup()}>导出本地备份</button><button className="button secondary" type="button" onClick={() => void authAdapter.signOut().then(() => { setUser(null); setStatus("signed-out"); })}>退出登录</button><small>状态：{statusLabel[status]}</small></div> : <div className="sync-actions"><div className="auth-tabs"><button className={mode === "login" ? "active" : ""} type="button" onClick={() => setMode("login")}>登录</button><button className={mode === "signup" ? "active" : ""} type="button" onClick={() => setMode("signup")}>注册</button></div><label className="field"><span>邮箱</span><input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" autoComplete="email" /></label><label className="field"><span>密码</span><input type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="至少 6 位" autoComplete={mode === "signup" ? "new-password" : "current-password"} /></label><button className="button primary" type="button" disabled={loading || !email || password.length < 6} onClick={() => void submitAuth()}>{loading ? "处理中…" : mode === "login" ? "邮箱登录" : "创建账号"}</button><button className="button secondary" type="button" disabled={loading} onClick={() => void authAdapter.signInWithGoogle().catch((error) => setMessage(error instanceof Error ? error.message : "Google 登录失败"))}>使用 Google 登录</button><p className="auth-help">当前使用邮箱密码登录；邮箱确认由 Supabase 控制台决定。</p><button className="button secondary" type="button" onClick={() => void backup()}>导出本地备份（可选）</button></div>}{message && <p role="status">{message}</p>}</section>;
}
