import { useEffect, useState } from "react";
import type { DailyReview } from "../domain/models";
import { studyFlowApi } from "../features/api";
import { Modal } from "./Modal";

export function DailyReviewPanel({ localDate, plannedMinutes, completedMinutes, actualFocusMinutes }: { localDate: string; plannedMinutes: number; completedMinutes: number; actualFocusMinutes: number }) {
  const [review, setReview] = useState<DailyReview | undefined>(); const [open, setOpen] = useState(false);
  const [matchesExpectation, setMatchesExpectation] = useState<DailyReview["matchesExpectation"]>(null); const [blocker, setBlocker] = useState(""); const [nextStep, setNextStep] = useState("");
  useEffect(() => { void studyFlowApi.dailyReviews.get(localDate).then((value) => { setReview(value); if (value) { setMatchesExpectation(value.matchesExpectation); setBlocker(value.blocker); setNextStep(value.nextStep); } else if (new Date().getHours() >= 20) setOpen(true); }); }, [localDate]);
  async function save() { const value = await studyFlowApi.dailyReviews.save({ localDate, timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, plannedMinutes, completedMinutes, actualFocusMinutes, matchesExpectation, blocker, nextStep }); setReview(value); setOpen(false); }
  return <section className="daily-review-card"><div><p className="eyebrow">每日复盘</p><h2>{review ? "今天的复盘已保存" : "让明天的计划更贴近现实"}</h2><p>计划 {plannedMinutes} 分钟 · 完成 {completedMinutes} 分钟 · 实际专注 {actualFocusMinutes} 分钟</p></div><button className="button secondary" onClick={() => setOpen(true)}>{review ? "查看复盘" : "开始复盘"}</button>{open && <Modal title="每日复盘" onClose={() => setOpen(false)}><div className="task-form"><label className="field field-wide">今天的进度是否符合预期？<select value={matchesExpectation ?? ""} onChange={(event) => setMatchesExpectation((event.target.value || null) as DailyReview["matchesExpectation"])}><option value="">暂不判断</option><option value="yes">符合预期</option><option value="partly">部分符合</option><option value="no">不符合预期</option></select></label><label className="field field-wide">最大的阻碍<textarea value={blocker} maxLength={1000} onChange={(event) => setBlocker(event.target.value)} placeholder="例如：低估了习题难度" /></label><label className="field field-wide">明天最重要的一步<textarea value={nextStep} maxLength={1000} onChange={(event) => setNextStep(event.target.value)} placeholder="例如：先完成 CS50 Week 2 的第一题" /></label><footer className="modal-actions field-wide"><button className="button secondary" onClick={() => setOpen(false)}>稍后</button><button className="button primary" onClick={() => void save()}>保存复盘</button></footer></div></Modal>}</section>;
}
