import { useState, type FormEvent } from "react";
import type { FailureReason, FinishSessionInput, SessionOutcome, StudySession } from "../features/executionTypes";
import { formatDuration } from "../features/executionAdapter";
import { Modal } from "./Modal";

const reasons = [["underestimated", "低估任务难度"], ["insufficient-time", "可用时间不足"], ["interrupted", "被其他事情打断"], ["low-energy", "状态不佳"], ["plan-changed", "学习计划改变"], ["other", "其他"]] as const;
export function FinishSessionModal({ session, focusSeconds, onClose, onFinish }: { session: StudySession; focusSeconds: number; onClose: () => void; onFinish: (input: FinishSessionInput) => Promise<void> }) {
  const [result, setResult] = useState<SessionOutcome>("completed"); const [reason, setReason] = useState<FailureReason | "">(""); const [summary, setSummary] = useState(""); const [note, setNote] = useState(""); const [completeTask, setCompleteTask] = useState(Boolean(session.taskId)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: FormEvent) { event.preventDefault(); if (result !== "completed" && !reason) return setError("请选择未完全完成的原因"); setBusy(true); setError(""); try { await onFinish({ outcome: result, failureReason: reason || null, summary: summary.trim(), note: note.trim(), completeTask: result === "completed" && completeTask }); } catch (cause) { setError(cause instanceof Error ? cause.message : "保存失败"); setBusy(false); } }
  return <Modal title="结束本次学习" onClose={onClose}><form className="finish-form" onSubmit={(event) => void submit(event)}><div className="finish-summary"><span>有效专注</span><strong>{formatDuration(focusSeconds)}</strong><small>{session.taskTitleSnapshot}</small></div><fieldset className="result-picker"><legend>本次结果</legend>{([['completed','完成'],['partial','部分完成'],['unfinished','未完成']] as const).map(([value,label]) => <label className={result === value ? "selected" : ""} key={value}><input type="radio" name="result" checked={result === value} onChange={() => setResult(value)} />{label}</label>)}</fieldset>{result !== "completed" && <label className="field">主要原因<select value={reason} onChange={(e) => setReason(e.target.value as FailureReason | "")}><option value="">请选择</option>{reasons.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label>}<label className="field">学习总结（可选）<textarea value={summary} maxLength={5000} placeholder="今天学会了什么？" onChange={(e) => setSummary(e.target.value)} /></label><label className="field">补充备注（可选）<textarea value={note} maxLength={2000} placeholder="记录下次继续时需要注意的内容" onChange={(e) => setNote(e.target.value)} /></label>{result === "completed" && session.taskId && <label className="check-line"><input type="checkbox" checked={completeTask} onChange={(e) => setCompleteTask(e.target.checked)} />同时将关联任务标记为完成</label>}{focusSeconds < 60 && <p className="inline-warning">有效专注不足 1 分钟，结束后这条会话不会进入历史统计。</p>}{error && <p className="form-error" role="alert">{error}</p>}<footer className="modal-actions"><button className="button secondary" type="button" onClick={onClose}>继续学习</button><button className="button primary" disabled={busy}>{busy ? "正在保存…" : "确认结束"}</button></footer></form></Modal>;
}
