import { useEffect, useState, type FormEvent } from "react";
import type { FailureReason, SessionCorrectionInput, SessionOutcome, StudyInterval, StudySession } from "../features/executionTypes";
import { executionAdapter } from "../features/executionAdapter";
import { Modal } from "./Modal";
const reasons=[["underestimated","低估任务难度"],["insufficient-time","可用时间不足"],["interrupted","被其他事情打断"],["low-energy","状态不佳"],["plan-changed","学习计划改变"],["other","其他"]] as const;
const localValue=(iso:string|null)=>{if(!iso)return "";const value=new Date(iso);return `${value.getFullYear()}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}T${String(value.getHours()).padStart(2,"0")}:${String(value.getMinutes()).padStart(2,"0")}`};
const isoValue=(local:string)=>new Date(local).toISOString();
export function SessionCorrectionModal({session,intervals=[],onClose,onSave}:{session:StudySession;intervals?:StudyInterval[];onClose:()=>void;onSave:(input:SessionCorrectionInput)=>Promise<void>}){
 const [outcome,setOutcome]=useState<SessionOutcome>(session.outcome??"partial"),[failureReason,setFailureReason]=useState<FailureReason|"">(session.failureReason??""),[note,setNote]=useState(session.note),[summary,setSummary]=useState(session.summary),[timeline,setTimeline]=useState(()=>structuredClone(intervals)),[revisionReason,setRevisionReason]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(timeline.length===0)void executionAdapter.listIntervals(session.id).then(items=>setTimeline(structuredClone(items))).catch(()=>setError("读取时间线失败"))},[session.id,timeline.length]);
 function updateInterval(index:number,patch:Partial<StudyInterval>){setTimeline(items=>items.map((item,i)=>i===index?{...item,...patch,updatedAt:new Date().toISOString()}:item))}
 function updatePause(intervalIndex:number,pauseIndex:number,key:"startedAt"|"endedAt",value:string){setTimeline(items=>items.map((item,i)=>i!==intervalIndex?item:{...item,pauses:item.pauses.map((pause,p)=>p!==pauseIndex?pause:{...pause,[key]:value?isoValue(value):null}),updatedAt:new Date().toISOString()}))}
 async function submit(e:FormEvent){e.preventDefault();if(outcome!=="completed"&&!failureReason)return setError("请选择未完全完成的原因");if(!revisionReason.trim())return setError("请填写修正原因，修正记录将永久保留");if(timeline.some(item=>item.endedAt&&Date.parse(item.endedAt)<Date.parse(item.startedAt)))return setError("阶段结束时间不能早于开始时间");setBusy(true);try{await onSave({outcome,failureReason:outcome==="completed"?null:failureReason||null,note,summary,intervals:timeline,revisionReason:revisionReason.trim()})}catch(cause){setError(cause instanceof Error?cause.message:"修正失败");setBusy(false)}}
 return <Modal title="修正执行记录" onClose={onClose}><form className="finish-form correction-form" onSubmit={e=>void submit(e)}><p className="confirm-copy">修正不会覆盖原始历史，StudyFlow 会保留修改前后的值、时间线和原因。</p><label className="field">执行结果<select value={outcome} onChange={e=>setOutcome(e.target.value as SessionOutcome)}><option value="completed">完成</option><option value="partial">部分完成</option><option value="unfinished">未完成</option></select></label>{outcome!=="completed"&&<label className="field">主要原因<select value={failureReason} onChange={e=>setFailureReason(e.target.value as FailureReason|"")}><option value="">请选择</option>{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<fieldset className="timeline-editor"><legend>时间线</legend>{timeline.map((interval,index)=><article key={interval.id}><strong>{interval.kind==="focus"?"专注":"休息"} · 阶段 {index+1}</strong><div className="timeline-row"><label className="field">开始<input type="datetime-local" value={localValue(interval.startedAt)} onChange={e=>updateInterval(index,{startedAt:isoValue(e.target.value)})}/></label><label className="field">结束<input type="datetime-local" value={localValue(interval.endedAt)} onChange={e=>updateInterval(index,{endedAt:e.target.value?isoValue(e.target.value):null})}/></label></div>{interval.pauses.map((pause,pauseIndex)=><div className="timeline-row pause-row" key={`${interval.id}-${pauseIndex}`}><label className="field">暂停开始<input type="datetime-local" value={localValue(pause.startedAt)} onChange={e=>updatePause(index,pauseIndex,"startedAt",e.target.value)}/></label><label className="field">暂停结束<input type="datetime-local" value={localValue(pause.endedAt)} onChange={e=>updatePause(index,pauseIndex,"endedAt",e.target.value)}/></label></div>)}</article>)}</fieldset><label className="field">学习总结<textarea value={summary} onChange={e=>setSummary(e.target.value)}/></label><label className="field">备注<textarea value={note} onChange={e=>setNote(e.target.value)}/></label><label className="field">修正原因（必填）<textarea value={revisionReason} placeholder="为什么需要修正这条记录？" onChange={e=>setRevisionReason(e.target.value)}/></label>{error&&<p className="form-error">{error}</p>}<footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={busy}>保存修正</button></footer></form></Modal>
}
